server:
  port: 9411
 
spring:
  application:
    name: springcloud-zipkin
    
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
      
management:
  metrics:
    web:
      server:
        auto-time-requests: false