server:
  port: 7003
 
eureka:
  instance:
    #hostname: localhost
    hostname: eureka7003.com
  client:
    #是否向注册中心注册自己
    register-with-eureka: false
    #是否从注册中心查询服务
    fetch-registry: false
    #注册中心地址
    service-url: 
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      
spring:    
  zipkin:
    base-url: http://localhost:9411